### ISSUE TITLE
Migration from the original project to this fork

### ISSUE THREAD

**Issue by sfondev** [Komorebi-Fork/komorebi#57]
Greetings, I've been using komorebi(the original) for some time now on Ubuntu 18.04 (Laptop,dual boot with windows10,single screen) and I haven't had any problems with it.
Yesterday I was doing some browsing online and found someone linking to this new fork of the project that seems to be more updated/active.

I have some questions about this fork:
- Should I install it even if I don't have problems with the older one?
- If I install it will it replace the older project already installed(and with it delete the wallpapers I already had)?
- If it doesn't delete the older wallpapers will the new installation detect the wallpapers already created and detected by komorebi before the installation of this new fork?
- If I upgrade from 18.04 to 20.04 will I have any problem with komorebi(like dependency related stuff or others)? (I've seen on the readme that 20.04 is tested working but my question is in case of  doing distro upgrade and not a new install)

Sorry to be asking this questions here on the issues of the project but I don't know if there is a better place to do it.

**Comment by Ev1lbl0w** [comment]
> Should I install it even if I don't have problems with the older one?

Well, the good rule of thumb is to not fix what's not broken :stuck_out_tongue:. If you find an issue however, since the original project is dead, we can only fix it on this fork.

> If I install it will it replace the older project already installed(and with it delete the wallpapers I already had)?

It won't because the old project uses some rather unconventional paths (`/System/Applications` and `/System/Resources`). We have changed the paths on this fork to more conventional Linux paths, so in theory there should be minimal interference with both versions; regarding wallpapers, it won't overwrite any of your custom ones.

However, can't say for sure if removing the old package will remove your custom wallpapers, so I'd copy them just in case, if you intend to switch to this fork.

> If it doesn't delete the older wallpapers will the new installation detect the wallpapers already created and detected by komorebi before the installation of this new fork?

This new version will import the old configuration file to a new path, but **not** the wallpapers, sorry. That's something very useful, so it would be cool to implement some day. But for now, to use your custom wallpapers with this fork, you need to move them from `/System/Resources/<wallpaper name>` to `~/.config/komorebi/wallpapers/`.

> If I upgrade from 18.04 to 20.04 will I have any problem with komorebi(like dependency related stuff or others)? (I've seen on the readme that 20.04 is tested working but my question is in case of doing distro upgrade and not a new install)

I'm not sure; from the looks of it, upgrades look problematic (#56 and https://github.com/cheesecakeufo/komorebi/issues/246), still haven't had much time to look into it. The test results in the homepage are made on clean VMs.

**Comment by sfondev** [comment]
Thanks for the quick answer and for continuing the development! When I end up updating to 20.04 I'll probably change to this fork then since for now komorebi is working as expected(at least for my usecases).
